#pragma once

// clang-format off
typedef enum {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, STAR, SLASH,
    MINUS, PLUS,
    SEMICOLON, COLON, COLON_EQUAL,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    IDENTIFIER, STRING, NUMBER,
    AND, OR,
    CLASS,
    IF, ELSE,
    TRUE, FALSE,
    FUNC,
    FOR, WHILE,
    NIL,
    PRINT,
    RETURN,
    SUPER, THIS,
    VAR,
    INT, FLOAT, ARRAY,
    ENDOFFILE
} TOKEN_TYPE;
// clang-format on
